### ISSUE TITLE
你們認為下個版本要優化什麼字形呢？

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [mant0u0/MantouSans#2]
饅頭黑體目前為日本字形（JIS2004），如果要優化字形，那麼你們認為是什麼標準的字形呢？

**Comment by mant0u0** [comment]
您好！很高興你的回覆！
目前的計畫，會先根據原字型將常用繁體中文字先補齊。至於不同的字形規格，未來如果常用字補完，順利的話再來慢慢修改了。感謝！( •̀∀•́ )

**Comment by UltimateAmitieKaiNiC** [comment]
那謝謝你了！
